#!/bin/bash

# Check if running inside Docker
if [ -f "/.dockerenv" ]; then
    # Modify the hosts file inside the Docker container
    echo "127.0.0.2 localhost" >> /etc/hosts
    echo "8.8.8.8 facebook.com" >> /etc/hosts
else
    # Modify the hosts file on the host machine
    echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
    echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
fi
