#!/usr/bin/env bash
# Create a new hosts file
cp /etc/hosts ~/hosts.new
# Update localhost entry
sed -i 's/.*localhost$/127.0.0.2 localhost/g' ~/hosts.new
# Remove existing facebook.com entry
sed -i '/facebook.com/d' ~/hosts.new
# Add new facebook.com entry
echo '8.8.8.8 facebook.com' >> ~/hosts.new
# Replace the original hosts file with the updated one
sudo cp ~/hosts.new /etc/hosts
# Clean up the temporary hosts file
rm ~/hosts.new
